export const nutritionData = {
  dog: [
    // Puppy (0-6 mo)
    {
      age: 'Puppy (0-6 mo)',
      weight: '5-10 lbs',
      activity: 'Normal',
      calories: '300-450 kcal',
      protein: '20-30%',
      fat: '15-20%',
    },
    {
      age: 'Puppy (0-6 mo)',
      weight: '5-10 lbs',
      activity: 'Active',
      calories: '350-500 kcal',
      protein: '25-35%',
      fat: '18-25%',
    },
    {
      age: 'Puppy (0-6 mo)',
      weight: '5-10 lbs',
      activity: 'Overweight',
      calories: '250-350 kcal',
      protein: '18-25%',
      fat: '12-16%',
    },
    {
      age: 'Puppy (0-6 mo)',
      weight: '10-25 lbs',
      activity: 'Normal',
      calories: '450-600 kcal',
      protein: '25-35%',
      fat: '18-25%',
    },
    {
      age: 'Puppy (0-6 mo)',
      weight: '10-25 lbs',
      activity: 'Active',
      calories: '500-700 kcal',
      protein: '30-40%',
      fat: '20-28%',
    },
    {
      age: 'Puppy (0-6 mo)',
      weight: '10-25 lbs',
      activity: 'Overweight',
      calories: '350-500 kcal',
      protein: '20-30%',
      fat: '15-20%',
    },
    {
      age: 'Puppy (0-6 mo)',
      weight: '25-50 lbs',
      activity: 'Normal',
      calories: '600-900 kcal',
      protein: '30-40%',
      fat: '20-28%',
    },
    {
      age: 'Puppy (0-6 mo)',
      weight: '25-50 lbs',
      activity: 'Active',
      calories: '700-1000 kcal',
      protein: '35-45%',
      fat: '25-32%',
    },
    {
      age: 'Puppy (0-6 mo)',
      weight: '25-50 lbs',
      activity: 'Overweight',
      calories: '500-700 kcal',
      protein: '25-35%',
      fat: '18-25%',
    },

    // Adult (1-7 yr)
    {
      age: 'Adult (1-7 yr)',
      weight: '5-10 lbs',
      activity: 'Normal',
      calories: '200-300 kcal',
      protein: '15-20%',
      fat: '10-15%',
    },
    {
      age: 'Adult (1-7 yr)',
      weight: '5-10 lbs',
      activity: 'Active',
      calories: '250-350 kcal',
      protein: '18-25%',
      fat: '12-18%',
    },
    {
      age: 'Adult (1-7 yr)',
      weight: '5-10 lbs',
      activity: 'Overweight',
      calories: '150-250 kcal',
      protein: '12-18%',
      fat: '8-12%',
    },
    {
      age: 'Adult (1-7 yr)',
      weight: '10-25 lbs',
      activity: 'Normal',
      calories: '300-450 kcal',
      protein: '18-25%',
      fat: '12-18%',
    },
    {
      age: 'Adult (1-7 yr)',
      weight: '10-25 lbs',
      activity: 'Active',
      calories: '350-500 kcal',
      protein: '20-28%',
      fat: '15-20%',
    },
    {
      age: 'Adult (1-7 yr)',
      weight: '10-25 lbs',
      activity: 'Overweight',
      calories: '250-350 kcal',
      protein: '15-22%',
      fat: '10-15%',
    },
    {
      age: 'Adult (1-7 yr)',
      weight: '25-50 lbs',
      activity: 'Normal',
      calories: '450-650 kcal',
      protein: '20-28%',
      fat: '15-20%',
    },
    {
      age: 'Adult (1-7 yr)',
      weight: '25-50 lbs',
      activity: 'Active',
      calories: '500-750 kcal',
      protein: '25-32%',
      fat: '18-25%',
    },
    {
      age: 'Adult (1-7 yr)',
      weight: '25-50 lbs',
      activity: 'Overweight',
      calories: '350-500 kcal',
      protein: '18-25%',
      fat: '12-18%',
    },

    // Senior (7+ yr)
    {
      age: 'Senior (7+ yr)',
      weight: '5-10 lbs',
      activity: 'Normal',
      calories: '150-250 kcal',
      protein: '12-18%',
      fat: '8-12%',
    },
    {
      age: 'Senior (7+ yr)',
      weight: '5-10 lbs',
      activity: 'Active',
      calories: '200-300 kcal',
      protein: '15-20%',
      fat: '10-15%',
    },
    {
      age: 'Senior (7+ yr)',
      weight: '5-10 lbs',
      activity: 'Overweight',
      calories: '120-200 kcal',
      protein: '10-15%',
      fat: '6-10%',
    },
    {
      age: 'Senior (7+ yr)',
      weight: '10-25 lbs',
      activity: 'Normal',
      calories: '250-400 kcal',
      protein: '15-22%',
      fat: '10-15%',
    },
    {
      age: 'Senior (7+ yr)',
      weight: '10-25 lbs',
      activity: 'Active',
      calories: '300-450 kcal',
      protein: '18-25%',
      fat: '12-18%',
    },
    {
      age: 'Senior (7+ yr)',
      weight: '10-25 lbs',
      activity: 'Overweight',
      calories: '200-300 kcal',
      protein: '12-18%',
      fat: '8-12%',
    },
    {
      age: 'Senior (7+ yr)',
      weight: '25-50 lbs',
      activity: 'Normal',
      calories: '400-600 kcal',
      protein: '18-25%',
      fat: '12-18%',
    },
    {
      age: 'Senior (7+ yr)',
      weight: '25-50 lbs',
      activity: 'Active',
      calories: '450-650 kcal',
      protein: '20-28%',
      fat: '15-20%',
    },
    {
      age: 'Senior (7+ yr)',
      weight: '25-50 lbs',
      activity: 'Overweight',
      calories: '300-450 kcal',
      protein: '15-22%',
      fat: '10-15%',
    },
  ],
  cat: [
    // Kitten (0-6 mo)
    {
      age: 'Kitten (0-6 mo)',
      weight: '2-5 lbs',
      activity: 'Normal',
      calories: '200-250 kcal',
      protein: '18-24%',
      fat: '8-12%',
    },
    {
      age: 'Kitten (0-6 mo)',
      weight: '2-5 lbs',
      activity: 'Active',
      calories: '220-270 kcal',
      protein: '20-26%',
      fat: '10-14%',
    },
    {
      age: 'Kitten (0-6 mo)',
      weight: '2-5 lbs',
      activity: 'Overweight',
      calories: '180-230 kcal',
      protein: '16-22%',
      fat: '6-10%',
    },
    {
      age: 'Kitten (0-6 mo)',
      weight: '5-10 lbs',
      activity: 'Normal',
      calories: '250-300 kcal',
      protein: '20-26%',
      fat: '10-14%',
    },
    {
      age: 'Kitten (0-6 mo)',
      weight: '5-10 lbs',
      activity: 'Active',
      calories: '270-320 kcal',
      protein: '22-28%',
      fat: '12-16%',
    },
    {
      age: 'Kitten (0-6 mo)',
      weight: '5-10 lbs',
      activity: 'Overweight',
      calories: '230-280 kcal',
      protein: '18-24%',
      fat: '8-12%',
    },
    {
      age: 'Kitten (0-6 mo)',
      weight: '10-15 lbs',
      activity: 'Normal',
      calories: '300-350 kcal',
      protein: '22-28%',
      fat: '12-16%',
    },
    {
      age: 'Kitten (0-6 mo)',
      weight: '10-15 lbs',
      activity: 'Active',
      calories: '320-370 kcal',
      protein: '24-30%',
      fat: '14-18%',
    },
    {
      age: 'Kitten (0-6 mo)',
      weight: '10-15 lbs',
      activity: 'Overweight',
      calories: '280-330 kcal',
      protein: '20-26%',
      fat: '10-14%',
    },

    // Adult (1-10 yr)
    {
      age: 'Adult (1-10 yr)',
      weight: '2-5 lbs',
      activity: 'Normal',
      calories: '150-180 kcal',
      protein: '18-22%',
      fat: '8-12%',
    },
    {
      age: 'Adult (1-10 yr)',
      weight: '2-5 lbs',
      activity: 'Active',
      calories: '180-220 kcal',
      protein: '20-25%',
      fat: '10-14%',
    },
    {
      age: 'Adult (1-10 yr)',
      weight: '2-5 lbs',
      activity: 'Overweight',
      calories: '120-160 kcal',
      protein: '15-20%',
      fat: '6-10%',
    },
    {
      age: 'Adult (1-10 yr)',
      weight: '5-10 lbs',
      activity: 'Normal',
      calories: '180-220 kcal',
      protein: '20-25%',
      fat: '10-14%',
    },
    {
      age: 'Adult (1-10 yr)',
      weight: '5-10 lbs',
      activity: 'Active',
      calories: '220-260 kcal',
      protein: '24-28%',
      fat: '12-16%',
    },
    {
      age: 'Adult (1-10 yr)',
      weight: '5-10 lbs',
      activity: 'Overweight',
      calories: '150-200 kcal',
      protein: '18-22%',
      fat: '8-12%',
    },
    {
      age: 'Adult (1-10 yr)',
      weight: '10-15 lbs',
      activity: 'Normal',
      calories: '220-260 kcal',
      protein: '22-27%',
      fat: '12-16%',
    },
    {
      age: 'Adult (1-10 yr)',
      weight: '10-15 lbs',
      activity: 'Active',
      calories: '260-300 kcal',
      protein: '26-30%',
      fat: '14-18%',
    },
    {
      age: 'Adult (1-10 yr)',
      weight: '10-15 lbs',
      activity: 'Overweight',
      calories: '180-220 kcal',
      protein: '20-24%',
      fat: '10-14%',
    },

    // Senior (10+ yr)
    {
      age: 'Senior (10+ yr)',
      weight: '2-5 lbs',
      activity: 'Normal',
      calories: '130-170 kcal',
      protein: '16-20%',
      fat: '6-10%',
    },
    {
      age: 'Senior (10+ yr)',
      weight: '2-5 lbs',
      activity: 'Active',
      calories: '160-200 kcal',
      protein: '18-22%',
      fat: '8-12%',
    },
    {
      age: 'Senior (10+ yr)',
      weight: '2-5 lbs',
      activity: 'Overweight',
      calories: '110-150 kcal',
      protein: '14-18%',
      fat: '4-8%',
    },
    {
      age: 'Senior (10+ yr)',
      weight: '5-10 lbs',
      activity: 'Normal',
      calories: '150-200 kcal',
      protein: '18-22%',
      fat: '8-12%',
    },
    {
      age: 'Senior (10+ yr)',
      weight: '5-10 lbs',
      activity: 'Active',
      calories: '180-230 kcal',
      protein: '20-25%',
      fat: '10-14%',
    },
    {
      age: 'Senior (10+ yr)',
      weight: '5-10 lbs',
      activity: 'Overweight',
      calories: '130-180 kcal',
      protein: '15-20%',
      fat: '6-10%',
    },
    {
      age: 'Senior (10+ yr)',
      weight: '10-15 lbs',
      activity: 'Normal',
      calories: '180-230 kcal',
      protein: '20-24%',
      fat: '10-14%',
    },
    {
      age: 'Senior (10+ yr)',
      weight: '10-15 lbs',
      activity: 'Active',
      calories: '210-260 kcal',
      protein: '22-26%',
      fat: '12-16%',
    },
    {
      age: 'Senior (10+ yr)',
      weight: '10-15 lbs',
      activity: 'Overweight',
      calories: '160-200 kcal',
      protein: '18-22%',
      fat: '8-12%',
    },
  ],
  rabbit: [
    // Young (0-6 mo)
    {
      age: 'Young (0-6 mo)',
      weight: '1-4 lbs',
      activity: 'Normal',
      calories: '200-250 kcal',
      protein: '18-20%',
      fat: 'N/A',
    },
    {
      age: 'Young (0-6 mo)',
      weight: '1-4 lbs',
      activity: 'Active',
      calories: '250-300 kcal',
      protein: '18-20%',
      fat: 'N/A',
    },
    {
      age: 'Young (0-6 mo)',
      weight: '1-4 lbs',
      activity: 'Overweight',
      calories: '150-200 kcal',
      protein: '18-20%',
      fat: 'N/A',
    },
    {
      age: 'Young (0-6 mo)',
      weight: '4-7 lbs',
      activity: 'Normal',
      calories: '250-300 kcal',
      protein: '18-20%',
      fat: 'N/A',
    },
    {
      age: 'Young (0-6 mo)',
      weight: '4-7 lbs',
      activity: 'Active',
      calories: '300-350 kcal',
      protein: '18-20%',
      fat: 'N/A',
    },
    {
      age: 'Young (0-6 mo)',
      weight: '4-7 lbs',
      activity: 'Overweight',
      calories: '200-250 kcal',
      protein: '18-20%',
      fat: 'N/A',
    },
    {
      age: 'Young (0-6 mo)',
      weight: '7-10 lbs',
      activity: 'Normal',
      calories: '300-350 kcal',
      protein: '18-20%',
      fat: 'N/A',
    },
    {
      age: 'Young (0-6 mo)',
      weight: '7-10 lbs',
      activity: 'Active',
      calories: '350-400 kcal',
      protein: '18-20%',
      fat: 'N/A',
    },
    {
      age: 'Young (0-6 mo)',
      weight: '7-10 lbs',
      activity: 'Overweight',
      calories: '250-300 kcal',
      protein: '18-20%',
      fat: 'N/A',
    },

    // Adult (6 mo - 5 yr)
    {
      age: 'Adult (6 mo - 5 yr)',
      weight: '1-4 lbs',
      activity: 'Normal',
      calories: '150-200 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Adult (6 mo - 5 yr)',
      weight: '1-4 lbs',
      activity: 'Active',
      calories: '200-250 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Adult (6 mo - 5 yr)',
      weight: '1-4 lbs',
      activity: 'Overweight',
      calories: '100-150 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Adult (6 mo - 5 yr)',
      weight: '4-7 lbs',
      activity: 'Normal',
      calories: '200-250 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Adult (6 mo - 5 yr)',
      weight: '4-7 lbs',
      activity: 'Active',
      calories: '250-300 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Adult (6 mo - 5 yr)',
      weight: '4-7 lbs',
      activity: 'Overweight',
      calories: '150-200 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Adult (6 mo - 5 yr)',
      weight: '7-10 lbs',
      activity: 'Normal',
      calories: '250-300 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Adult (6 mo - 5 yr)',
      weight: '7-10 lbs',
      activity: 'Active',
      calories: '300-350 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Adult (6 mo - 5 yr)',
      weight: '7-10 lbs',
      activity: 'Overweight',
      calories: '200-250 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },

    // Senior (5+ yr)
    {
      age: 'Senior (5+ yr)',
      weight: '1-4 lbs',
      activity: 'Normal',
      calories: '120-150 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Senior (5+ yr)',
      weight: '1-4 lbs',
      activity: 'Active',
      calories: '150-200 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Senior (5+ yr)',
      weight: '1-4 lbs',
      activity: 'Overweight',
      calories: '100-120 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Senior (5+ yr)',
      weight: '4-7 lbs',
      activity: 'Normal',
      calories: '150-200 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Senior (5+ yr)',
      weight: '4-7 lbs',
      activity: 'Active',
      calories: '200-250 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Senior (5+ yr)',
      weight: '4-7 lbs',
      activity: 'Overweight',
      calories: '120-150 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Senior (5+ yr)',
      weight: '7-10 lbs',
      activity: 'Normal',
      calories: '200-250 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Senior (5+ yr)',
      weight: '7-10 lbs',
      activity: 'Active',
      calories: '250-300 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
    {
      age: 'Senior (5+ yr)',
      weight: '7-10 lbs',
      activity: 'Overweight',
      calories: '150-200 kcal',
      protein: '20-25%',
      fat: 'N/A',
    },
  ],
};
